name: CI

on:
  push:
    branches: [ main ]
    tags: [v*]
  pull_request:
    branches: [ main ]

  release:

  workflow_dispatch:
  
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@v1.1
        with:
          version: 1.59.0

      - uses: actions/checkout@v2

      - name: Setup
        run: make setup
      - name: Configure
        run: make init
      - name: Build 
        run: make

  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Integration tests
        run: make docker-integration-tests

  docker:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: tokheim/amqpproxy
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
