name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  release:

  workflow_dispatch:
  
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@v1.1
        with:
          version: 1.59.0

      - uses: actions/checkout@v2

      - name: Setup
        run: make setup
      - name: Configure
        run: make init
      - name: Build 
        run: make

  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Integration tests
        run: make docker-integration-tests
